<a href="https://colab.research.google.com/github/lexxai/goit_python_ds_hw_01/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

# Task 1

In [10]:
task1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(f"{task1=}")
task1_1 = np.arange(0,10)
print(f"{task1_1=}")
task1_2 = np.linspace(0,9,num=10, dtype=int)
print(f"{task1_2=}")

task1=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
task1_1=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
task1_2=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# Task 2

In [11]:
task2 = np.zeros((3,3))
task2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
task2_1 = np.zeros(9).reshape(3,3)
task2_1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Task 3

In [13]:
task3 = np.random.randint(1, 10+1, size=(5,5))
task3

array([[ 1,  9,  7,  5,  4],
       [ 2,  3,  9,  9, 10],
       [ 3,  7,  5,  5,  9],
       [ 2,  9,  6,  1,  2],
       [ 9,  7,  8,  9,  7]])

# Task 4

In [14]:
task4 = np.random.random((4,4))
task4

array([[0.80641245, 0.49089118, 0.74818276, 0.75551154],
       [0.78260105, 0.68680224, 0.65618161, 0.06385118],
       [0.49535224, 0.04190866, 0.46195517, 0.83751217],
       [0.07449768, 0.50401704, 0.21043821, 0.51855612]])

# Task 5

In [15]:
task5_1 = np.random.random(5)
task5_1

array([0.60108428, 0.67404279, 0.33221513, 0.8700326 , 0.97222687])

In [16]:
task5_2 = np.random.random(5)
task5_2

array([0.89619977, 0.03382864, 0.15509794, 0.05274371, 0.46814147])

In [17]:
task5_1 + task5_2

array([1.49728405, 0.70787143, 0.48731307, 0.92277631, 1.44036834])

In [18]:
task5_1 - task5_2

array([-0.29511549,  0.64021415,  0.17711719,  0.81728888,  0.50408539])

In [19]:
task5_1 * task5_2

array([0.5386916 , 0.02280195, 0.05152588, 0.04588875, 0.45513972])

# Task 6

In [20]:
task6_1 = np.array([55,66,54,0,88,67,-89])
print(task6_1.shape)
task6_1


(7,)


array([ 55,  66,  54,   0,  88,  67, -89])

In [21]:
task6_2 = np.array([33,22,11,16,67,82,9])
print(task6_2.shape)
task6_2


(7,)


array([33, 22, 11, 16, 67, 82,  9])

In [22]:
np.dot(task6_1, task6_2)

14450

In [23]:
np.sum(task6_1*task6_2)

14450

# Task 7

In [24]:
task7_1 = np.random.randint(1,10+1,size=(2,2))
task7_1

array([[ 6,  5],
       [ 4, 10]])

In [25]:
task7_2 = np.random.randint(1,10+1,size=(2,3))
task7_2

array([[6, 5, 4],
       [8, 6, 4]])

In [26]:
np.dot(task7_1,task7_2)

array([[ 76,  60,  44],
       [104,  80,  56]])

# Task 8

In [27]:
task8_1 = np.random.randint(1,10+1,size=(3,3))
task8_1

array([[ 4,  5,  7],
       [10,  2,  2],
       [ 1,  5, 10]])

In [28]:
task8_1.T

array([[ 4, 10,  1],
       [ 5,  2,  5],
       [ 7,  2, 10]])

# Task 9

In [29]:
task9_1 = np.random.random(size=(4,4))
task9_1

array([[0.45685559, 0.24991001, 0.2032153 , 0.05418353],
       [0.45169312, 0.81298432, 0.51039829, 0.77331668],
       [0.50884956, 0.91155381, 0.09887302, 0.11900553],
       [0.02267161, 0.93691063, 0.60611966, 0.01620785]])

In [30]:
task9_1.T

array([[0.45685559, 0.45169312, 0.50884956, 0.02267161],
       [0.24991001, 0.81298432, 0.91155381, 0.93691063],
       [0.2032153 , 0.51039829, 0.09887302, 0.60611966],
       [0.05418353, 0.77331668, 0.11900553, 0.01620785]])

# Task 10

In [31]:
task10_1 = np.random.randint(1,10+1,size=(3,4))
task10_1

array([[6, 6, 8, 6],
       [5, 1, 4, 6],
       [2, 7, 6, 5]])

In [32]:
task10_2 = np.random.randint(1,10+1,size=(4))
task10_2

array([8, 3, 2, 3])

In [33]:
np.dot(task10_1, task10_2)

array([100,  69,  64])

# Task 11

In [34]:
task11_1 = np.random.random(size=(2,3))
task11_1

array([[0.17328838, 0.95000531, 0.61480015],
       [0.69989455, 0.82576052, 0.01945492]])

In [35]:
task11_2 = np.random.random(size=(3))
task11_2

array([0.85930307, 0.67284531, 0.4013015 ])

In [36]:
np.dot(task11_1, task11_2)

array([1.03483407, 1.16483791])

# Task 12

---



In [37]:
task12_1= np.random.randint(1,10+1,size=(2,2))
task12_1

array([[ 8,  6],
       [10,  3]])

In [45]:
task12_2= np.random.randint(1,10+1,size=(2,2))
task12_2

array([[ 3,  3],
       [10,  1]])

In [43]:
task12_1 * task12_2

array([[64, 12],
       [10, 18]])

# Task 13

In [46]:
task13_1= np.random.randint(1,10+1,size=(2,2))
task13_1

array([[ 4, 10],
       [ 4, 10]])

In [52]:
task13_2= np.random.randint(1,10+1,size=(2,2))
task13_2

array([[3, 6],
       [5, 7]])

In [51]:
np.dot(task13_1 , task13_2)

array([[78, 90],
       [78, 90]])

# Task 14

In [53]:
task14_1= np.random.randint(1,100+1,size=(5,5))
task14_1

array([[ 17,  94,  78,  16,  51],
       [ 96,  42,   4,   5,  97],
       [ 96,  92,  26,  88,  55],
       [ 86,  96,  50, 100,  60],
       [ 12,  29,  51,  22,  76]])

In [54]:
task14_1.sum()

1439

# Task 15

---



In [55]:
task15_1= np.random.randint(1,10+1,size=(4,4))
task15_1

array([[ 3,  7,  6,  9],
       [ 1, 10,  5, 10],
       [ 7,  5,  4,  1],
       [ 1,  4,  6,  5]])

In [56]:
task15_2= np.random.randint(1,10+1,size=(4,4))
task15_2

array([[ 8, 10,  2, 10],
       [ 2,  9,  7, 10],
       [ 5,  2,  1,  5],
       [ 7,  6,  4,  9]])

In [58]:
task15_1 - task15_2

array([[-5, -3,  4, -1],
       [-1,  1, -2,  0],
       [ 2,  3,  3, -4],
       [-6, -2,  2, -4]])

# Task 16

In [85]:
task16_1 = np.random.random(size=(3,3))
task16_1

array([[0.93498602, 0.00446034, 0.75066141],
       [0.56492146, 0.30573071, 0.59035059],
       [0.91820387, 0.94746311, 0.51810113]])

In [93]:
task16_1[0]

array([0.93498602, 0.00446034, 0.75066141])

In [94]:
task16_1[0].sum()

1.6901077624157637

In [95]:
task_16 = np.array([ task16_1[i].sum() for i in range( task16_1.shape[0])])
task_16


array([1.69010776, 1.46100276, 2.38376811])

In [96]:
task16_1.sum(axis=1)

array([1.69010776, 1.46100276, 2.38376811])

# Task 17

In [100]:
task17_1 = np.random.randint(1,10+1,size=(3,4))
task17_1

array([[ 7,  1,  8, 10],
       [ 4,  2,  7,  7],
       [ 8,  6,  3,  8]])

In [99]:
task17_2 = np.square(task17_1)
task17_2


array([[ 49,   4,  49,  81],
       [ 81,   1,  25,  36],
       [  1,  16,  81, 100]])

# Task 18

In [102]:
task18_1 = np.random.randint(1,50+1,size=(4))
task18_1

array([46, 38, 22, 22])

In [105]:
np.sqrt(task18_1)

array([6.78232998, 6.164414  , 4.69041576, 4.69041576])

In [106]:
np.power(task18_1, 0.5)

array([6.78232998, 6.164414  , 4.69041576, 4.69041576])